items-enabled: true # обрабатывать предметы, работает только на Paper 1.16.5 начиная с билда 735!!
entity-nametags-enabled: true # обрабатывать энтити
map-icons-enabled: true # Обрабатывать метки на картах
player-info-enabled: true # Обрабатывать имена игроков
server-motd-enabled: true # Обрабатывать мотд.
# Пакеты, содержащие в себе компоненты. Можете убрать те, которые вам не нужны.
# Думаю, разберётесь ;)
packets-to-listen:
  - KICK_DISCONNECT
  - BOSS
  - CHAT
  - OPEN_WINDOW
  - COMBAT_EVENT
  - SCOREBOARD_OBJECTIVE
  - SCOREBOARD_TEAM
  - TITLE
  - PLAYER_LIST_HEADER_FOOTER
